name             = Zigzag
version          = 0.70
author           = Andrew Pam <xanni@xanadu.net>
license          = Perl_5
copyright_holder = Andrew Pam

[@Git]
push_to          = kstar

[@Basic]

[PodSyntaxTests]
; [PodCoverageTests]
; [Test::Perl::Critic]
[PkgVersion]
[AutoPrereqs]
